### ISSUE TITLE
if a cron fires while connection is down, chronbot crashes

### ISSUE THREAD

**Issue by eastein** [eastein/chronbot#4]
Traceback (most recent call last):
  File "./chronbot", line 304, in <module>
    s.run()
  File "/home/eastein/newer_venv/local/lib/python2.7/site-packages/mediorc/**init**.py", line 103, in run
    self.client.do_work()
  File "./chronbot", line 279, in do_work
    self.core.do_work()
  File "./chronbot", line 90, in do_work
    self.bot.connection.privmsg(self.chan, msg)
  File "/home/eastein/newer_venv/local/lib/python2.7/site-packages/irc/client.py", line 886, in privmsg
    self.send_raw("PRIVMSG %s :%s" % (target, text))
  File "/home/eastein/newer_venv/local/lib/python2.7/site-packages/irc/client.py", line 916, in send_raw
    raise ServerNotConnectedError("Not connected.")
irc.client.ServerNotConnectedError: Not connected.

**Comment by eastein** [comment]
I believe this to be fixed.
